2015-01-12 10:22:57,705 - poeticjustice.views - INFO - Started
2015-01-12 10:23:12,297 - poeticjustice.views - ERROR - Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 113, in create_new_user_post
    .filter((~User).email_address==kwds['email_address'].lower())
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2278, in first
    ret = list(self[0:1])
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2145, in __getitem__
    return list(res)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2349, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2364, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/util/compat.py", line 195, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) column users.last_name does not exist
LINE 1: ...last_upd, users.profile_pic AS users_profile_pic, users.last...
                                                             ^
 'SELECT users.key AS users_key, users.initial_entry_by AS users_initial_entry_by, users.initial_entry_date AS users_initial_entry_date, users.last_uid AS users_last_uid, users.last_opr AS users_last_opr, users.last_upd AS users_last_upd, users.profile_pic AS users_profile_pic, users.last_name AS users_last_name, users.country_code AS users_country_code, users.email_address AS users_email_address, users.id AS users_id, users.city AS users_city, users.first_name AS users_first_name, users.open_id AS users_open_id, users.facebook_name AS users_facebook_name, users.auth_code AS users_auth_code, users.user_prefs AS users_user_prefs, users.user_name AS users_user_name, users.job_title AS users_job_title, users.website AS users_website, users.phone_number AS users_phone_number, users.post_code AS users_post_code, users.subnational AS users_subnational, users.address1 AS users_address1, users.address2 AS users_address2, users.is_active AS users_is_active, users.fax_number AS users_fax_number, users.mobile_number AS users_mobile_number, users.device_tokens AS users_device_tokens, users.password AS users_password, users.access_token AS users_access_token, users.twitter_name AS users_twitter_name, users.standin_for AS users_standin_for \nFROM users \nWHERE users.email_address = %(email_address_1)s \n LIMIT %(param_1)s' {'email_address_1': u'mat@miga.me', 'param_1': 1}
Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 113, in create_new_user_post
    .filter((~User).email_address==kwds['email_address'].lower())
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2278, in first
    ret = list(self[0:1])
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2145, in __getitem__
    return list(res)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2349, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/orm/query.py", line 2364, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/util/compat.py", line 195, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "build/bdist.macosx-10.9-x86_64/egg/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) column users.last_name does not exist
LINE 1: ...last_upd, users.profile_pic AS users_profile_pic, users.last...
                                                             ^
 'SELECT users.key AS users_key, users.initial_entry_by AS users_initial_entry_by, users.initial_entry_date AS users_initial_entry_date, users.last_uid AS users_last_uid, users.last_opr AS users_last_opr, users.last_upd AS users_last_upd, users.profile_pic AS users_profile_pic, users.last_name AS users_last_name, users.country_code AS users_country_code, users.email_address AS users_email_address, users.id AS users_id, users.city AS users_city, users.first_name AS users_first_name, users.open_id AS users_open_id, users.facebook_name AS users_facebook_name, users.auth_code AS users_auth_code, users.user_prefs AS users_user_prefs, users.user_name AS users_user_name, users.job_title AS users_job_title, users.website AS users_website, users.phone_number AS users_phone_number, users.post_code AS users_post_code, users.subnational AS users_subnational, users.address1 AS users_address1, users.address2 AS users_address2, users.is_active AS users_is_active, users.fax_number AS users_fax_number, users.mobile_number AS users_mobile_number, users.device_tokens AS users_device_tokens, users.password AS users_password, users.access_token AS users_access_token, users.twitter_name AS users_twitter_name, users.standin_for AS users_standin_for \nFROM users \nWHERE users.email_address = %(email_address_1)s \n LIMIT %(param_1)s' {'email_address_1': u'mat@miga.me', 'param_1': 1}
2015-01-12 10:31:38,538 - poeticjustice.views - INFO - Started
2015-01-12 10:31:48,865 - poeticjustice.views - ERROR - Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 125, in create_new_user_post
    str(user.id) + str(user.initial_entry_date) + default_hashkey
NameError: global name 'default_hashkey' is not defined
Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 125, in create_new_user_post
    str(user.id) + str(user.initial_entry_date) + default_hashkey
NameError: global name 'default_hashkey' is not defined
2015-01-12 10:40:56,160 - poeticjustice.views - INFO - Started
2015-01-12 10:41:33,685 - poeticjustice.views - ERROR - Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 133, in create_new_user_post
    user.save(session)
  File "/Users/mat/__src__/PoeticJusticeEnv/lib/python2.7/site-packages/Pyaella-0.7.1-py2.7.egg/pyaella/orm/__init__.py", line 610, in save
    raise ie
IntegrityError: (IntegrityError) null value in column "country_code" violates not-null constraint
DETAIL:  Failing row contains (null, postgres, 2015-01-12 18:41:33.681649, postgres, INSERT, 2015-01-12 18:41:33.681732, NODEVICETOKEN, null, null, ce85a4eaf4594a6fb0ae501fee6ed7106518f6bf2b4065a3c8b8f4a926f83797..., null, t, null, null, null, null, null, 1751aa189503994bd6c6d6ed3118e33c2981d2587980ab223750f52b509abd3a..., mat@miga.me, 11111).
 "INSERT INTO users (key, initial_entry_by, initial_entry_date, last_uid, last_opr, last_upd, device_token, profile_pic, subnational, access_token, user_name, is_active, facebook_name, twitter_name, country_code, mobile_number, user_prefs, password, email_address, id) VALUES (%(key)s, %(initial_entry_by)s, %(initial_entry_date)s, %(last_uid)s, %(last_opr)s, %(last_upd)s, %(device_token)s, %(profile_pic)s, %(subnational)s, %(access_token)s, %(user_name)s, %(is_active)s, %(facebook_name)s, %(twitter_name)s, %(country_code)s, %(mobile_number)s, %(user_prefs)s, %(password)s, %(email_address)s, nextval('users_id_seq')) RETURNING users.id" {'device_token': 'NODEVICETOKEN', 'profile_pic': None, 'country_code': None, 'subnational': None, 'last_opr': None, 'user_name': None, 'is_active': True, 'last_uid': None, 'access_token': 'ce85a4eaf4594a6fb0ae501fee6ed7106518f6bf2b4065a3c8b8f4a926f83797c8c1873942cef921bd6da56682cf00a5c42f13077584e36fe5d27683d75edb26', 'facebook_name': None, 'last_upd': datetime.datetime(2015, 1, 12, 10, 41, 33, 677412), 'twitter_name': None, 'key': None, 'mobile_number': None, 'user_prefs': None, 'password': '1751aa189503994bd6c6d6ed3118e33c2981d2587980ab223750f52b509abd3a9efccf51eed53905c424424d1f5fdbf17316d2d4b5f30d8063be4f315c210729', 'email_address': u'mat@miga.me', 'initial_entry_date': datetime.datetime(2015, 1, 12, 10, 41, 33, 677383), 'initial_entry_by': None}
Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 133, in create_new_user_post
    user.save(session)
  File "/Users/mat/__src__/PoeticJusticeEnv/lib/python2.7/site-packages/Pyaella-0.7.1-py2.7.egg/pyaella/orm/__init__.py", line 610, in save
    raise ie
IntegrityError: (IntegrityError) null value in column "country_code" violates not-null constraint
DETAIL:  Failing row contains (null, postgres, 2015-01-12 18:41:33.681649, postgres, INSERT, 2015-01-12 18:41:33.681732, NODEVICETOKEN, null, null, ce85a4eaf4594a6fb0ae501fee6ed7106518f6bf2b4065a3c8b8f4a926f83797..., null, t, null, null, null, null, null, 1751aa189503994bd6c6d6ed3118e33c2981d2587980ab223750f52b509abd3a..., mat@miga.me, 11111).
 "INSERT INTO users (key, initial_entry_by, initial_entry_date, last_uid, last_opr, last_upd, device_token, profile_pic, subnational, access_token, user_name, is_active, facebook_name, twitter_name, country_code, mobile_number, user_prefs, password, email_address, id) VALUES (%(key)s, %(initial_entry_by)s, %(initial_entry_date)s, %(last_uid)s, %(last_opr)s, %(last_upd)s, %(device_token)s, %(profile_pic)s, %(subnational)s, %(access_token)s, %(user_name)s, %(is_active)s, %(facebook_name)s, %(twitter_name)s, %(country_code)s, %(mobile_number)s, %(user_prefs)s, %(password)s, %(email_address)s, nextval('users_id_seq')) RETURNING users.id" {'device_token': 'NODEVICETOKEN', 'profile_pic': None, 'country_code': None, 'subnational': None, 'last_opr': None, 'user_name': None, 'is_active': True, 'last_uid': None, 'access_token': 'ce85a4eaf4594a6fb0ae501fee6ed7106518f6bf2b4065a3c8b8f4a926f83797c8c1873942cef921bd6da56682cf00a5c42f13077584e36fe5d27683d75edb26', 'facebook_name': None, 'last_upd': datetime.datetime(2015, 1, 12, 10, 41, 33, 677412), 'twitter_name': None, 'key': None, 'mobile_number': None, 'user_prefs': None, 'password': '1751aa189503994bd6c6d6ed3118e33c2981d2587980ab223750f52b509abd3a9efccf51eed53905c424424d1f5fdbf17316d2d4b5f30d8063be4f315c210729', 'email_address': u'mat@miga.me', 'initial_entry_date': datetime.datetime(2015, 1, 12, 10, 41, 33, 677383), 'initial_entry_by': None}
2015-01-12 10:57:32,080 - poeticjustice.views - INFO - Started
2015-01-12 18:03:19,196 - poeticjustice.views - INFO - Started
2015-01-13 07:54:54,819 - poeticjustice.views - INFO - Started
2015-01-13 08:10:29,882 - poeticjustice.views - INFO - Started
2015-01-13 08:14:06,242 - poeticjustice.views - INFO - Started
2015-01-13 08:14:52,801 - poeticjustice.views - INFO - Started
2015-01-13 09:28:40,027 - poeticjustice.views - INFO - Started
2015-01-13 09:28:54,617 - poeticjustice.views - ERROR - Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 135, in create_new_user_post
    grp_lut = LutValues(model=Group)
NameError: global name 'LutValues' is not defined
Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 135, in create_new_user_post
    grp_lut = LutValues(model=Group)
NameError: global name 'LutValues' is not defined
2015-01-13 09:31:17,274 - poeticjustice.views - INFO - Started
2015-01-13 09:57:24,814 - poeticjustice.views - INFO - Started
2015-01-13 13:30:08,783 - poeticjustice.views - INFO - Started
2015-01-13 13:34:38,611 - poeticjustice.views - ERROR - Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 254, in user_data
    user=get_current_user(auth_usrid, session=session)
NameError: global name 'auth_usrid' is not defined
Traceback (most recent call last):
  File "/Users/mat/__src__/PoeticJusticeEnv/Poeticjustice/poeticjustice/poeticjustice/views.py", line 254, in user_data
    user=get_current_user(auth_usrid, session=session)
NameError: global name 'auth_usrid' is not defined
2015-01-13 13:37:30,668 - poeticjustice.views - INFO - Started
2015-01-13 13:43:54,792 - poeticjustice.views - INFO - Started
2015-01-13 13:51:59,101 - poeticjustice.views - INFO - Started
2015-01-19 14:52:52,085 - poeticjustice.views - INFO - Started
2015-01-19 15:29:02,371 - poeticjustice.views - INFO - Started
